= Клиентский телеграмм-бот для отслеживания конкретных сообщений в чате/канале

* xref:description[Описание]
* xref:prerequisites[Пререквизиты]
* xref:run[Запуск]

[[description]]
== Описание

Проект представляет собой клиентского телеграмм-бота "API telegram client" (API для создания собственных клиентов).
Позволяет делать выборку на основе новых сообщений в чате и отправлять их на указанный аккаунт.
Выборка происходит путем нахождения в сообщении определенного слова/фразы.

Преимущество перед обычным телеграмм-ботом ("API telegram bot") в том, что чтение/отправка осуществляются через реальный телеграмм-аккаунт,
что позволяет обходить запрет от админов канала на вступление в него ботов.

[[prerequisites]]
== Пререквизиты

* ОС: Linux, Windows, MacOS
* Утилиты ОС: Python (v. 3.10), pip

[[run]]
== Запуск

1. Создание клиента телеграмма.
Необходимо зайти на сайт https://my.telegram.org и ввести необходимые данные.
Далее создаем клиент телеграмма: https://core.telegram.org/api#creating-an-application.
Заполняем поля App title и Short name, нажимаем «Create application» и запоминаем две переменные: api_id и api_hash
2. Настройка файла конфигурации .env.
Необходимо создать в корне проекта файл .env и скопировать в него информацию из .env.template.
После чего заполнить параметры (см. xref:params[Доступные параметры])
3. Скачать данный репозиторий к себе на компьютер
4. Установить зависимости из терминала в корне проекта: telethon и dotenv (pip install telethon и pip install python-dotenv)
5. Запустить скрипт из корня проекта: python main.py
6. При успешном запуске отобразится сообщение "Service started"

[[params]]
=== Доступные параметры

* API_ID - api_id, которое было получено при создании клиента телеграмма
* API_HASH - api_hash, который был получено при создании клиента телеграмма
* LISTENING_CHANNEL_ID - id чата/канала из которого читаются сообщения
* SEND_CHANNEL_ID - id чата/канала в который необходимо отправлять сообщения
* SEARCH_WORDS - слова по которым делается выборка сообщений (разделяются собой через запятую)

Пример:

----
API_ID = 12064535
API_HASH = qqqq8935d331233417622d6722aeqqqq
LISTENING_CHANNEL_ID = -1002004782419
SEND_CHANNEL_ID = -1001139874413
SEARCH_WORDS = #Minsk,Cat,Dog
----